[tox]
min_version = 4.24.1
basepython = python3.13
envlist =
    py313
    lint
    typecheck
isolated_build = true

[testenv]
package = editable
dependency_groups = dev
commands =
    pytest -m "not manual and not integration and not e2e and not real_env" --cov=fluentia --cov-report=term-missing --cov-report=xml --cov-report=html {posargs:tests}

[testenv:lint]
dependency_groups = dev
commands =
    ruff check .
    ruff format --check .
    pylint src/fluentia

[testenv:typecheck]
dependency_groups = dev
commands =
    mypy src/fluentia tests

[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
